apiVersion: apps/v1
kind: Deployment
metadata:
  name: mddev-limiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mddev-limiter
  template:
    metadata:
      labels:
        app: mddev-limiter
    spec:
      containers:
        - name: app
          image: fpommerening/container-training:limiter
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: ".50"
            limits:
              memory: "256Mi"
              cpu: "1.0"