apiVersion: batch/v1
kind: Job
metadata:
  name: onetime-work
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
        - name: app
          image: busybox:1.28
          command: ["sh", "-c", "echo The app is running! && sleep 45 && echo The work is done!"]
      restartPolicy: OnFailure
